export const MAX_WIDTH = "1440px";

export const ProvinceList = {
  Abruzzo: ["L'Aquila", "Teramo", "Pescara", "Chieti"],
  Basilicata: ["Potenza", "Matera"],
  Calabria: [
    "Catanzaro",
    "Cosenza",
    "Reggio Calabria",
    "Crotone",
    "Vibo Valentia",
  ],
  Campania: ["Napoli", "Avellino", "Benevento", "Caserta", "Salerno"],
  "Emilia-Romagna": [
    "Bologna",
    "Ferrara",
    "Forlì-Cesena",
    "Modena",
    "Parma",
    "Piacenza",
    "Ravenna",
    "Reggio Emilia",
  ],
  "Friuli-Venezia Giulia": ["Trieste", "Gorizia", "Udine", "Pordenone"],
  Lazio: ["Roma", "Frosinone", "Latina", "Rieti", "Viterbo"],
  Liguria: ["Genova", "Imperia", "La Spezia", "Savona"],
  Lombardia: [
    "Milano",
    "Bergamo",
    "Brescia",
    "Como",
    "Cremona",
    "Lecco",
    "Lodi",
    "Mantova",
    "Monza e Brianza",
    "Pavia",
    "Sondrio",
    "Varese",
  ],
  Marche: ["Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino"],
  Molise: ["Campobasso", "Isernia"],
  Piemonte: [
    "Torino",
    "Alessandria",
    "Asti",
    "Biella",
    "Cuneo",
    "Novara",
    "Verbano-Cusio-Ossola",
    "Vercelli",
  ],
  Puglia: [
    "Bari",
    "Barletta-Andria-Trani",
    "Brindisi",
    "Foggia",
    "Lecce",
    "Taranto",
  ],
  Sardegna: ["Cagliari", "Nuoro", "Oristano", "Sassari"],
  Sicilia: [
    "Palermo",
    "Agrigento",
    "Caltanissetta",
    "Catania",
    "Enna",
    "Messina",
    "Ragusa",
    "Siracusa",
    "Trapani",
  ],
  Toscana: [
    "Firenze",
    "Arezzo",
    "Grosseto",
    "Livorno",
    "Lucca",
    "Massa-Carrara",
    "Pisa",
    "Pistoia",
    "Prato",
    "Siena",
  ],
  "Trentino-Alto Adige": ["Trento", "Bolzano"],
  Umbria: ["Perugia", "Terni"],
  "Valle d'Aosta": ["Aosta"],
  Veneto: [
    "Venezia",
    "Belluno",
    "Padova",
    "Rovigo",
    "Treviso",
    "Verona",
    "Vicenza",
  ],
};
